import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";
import { notFound } from "next/navigation";
import { client } from "@/libs/client";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Category {
  category: string,
}

export default async function CategoryLayout({ params, children }: {
  children: React.ReactNode;
  params: Promise<Category>;
}) {
  const { category } = await params;

  async function getCategoryName() {
    try {
      const data = await client.get({
        endpoint: 'category',
        queries: {
          filters: `id[contains]${category}`,
        },
      });
      return data.contents;
    } catch {
      notFound();
    }
  }

  const categories = await getCategoryName();

  return (
    <div>
      <p>{categories[0].title}の記事一覧</p>
      {children}
      <Link href="/">トップに戻る</Link>
    </div>
  );
}
