import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      className={`${geistSans.variable} ${geistMono.variable} h-full`}
    >
      <body className="bg-white text-ink font-sans antialiased h-full antialiased flex flex-col">
        <Header />

        <main className="flex flex-col flex-1 items-center bg-zinc-50 font-sans flex flex-1">
          <div className="mx-auto w-full max-w-6xl px-4 py-8 md:px-8 md:py-12">
            <div className="mt-6 grid grid-cols-1 gap-6 md:grid-cols-2">
              {children}
            </div>
          </div>
        </main>

      </body>
    </html>
  );
}
